###
POST http://localhost:5000/todo/item HTTP/1.1
Content-Type: application/json

{
    "title": "Es una nueva tarea",
    "text": "Aca va a ir un texto re laaargo pero que ya fue no se que onda",
    "priority": 2,
    "status": true
}
###
GET http://localhost:5000/todo HTTP/1.1
###
GET http://localhost:5000/todo/get/FedeSca001 HTTP/1.1
###
PUT http://localhost:5000/todo/update/62dace714b59831eca3e7907 HTTP/1.1
Content-Type: application/json

{
    "title": "tercer update",
    "text": "a ver el header body",
    "priority": 8,
    "date": "",
    "status": false
}
###
DELETE http://localhost:5000/todo/delete HTTP/1.1

//USERS
###
POST http://localhost:5000/user/newUser HTTP/1.1
Content-Type: application/json

{
    "name": "FedeSca001",
    "lastName": "perritoMalvado",
    "password": "lcdtm1234"       
}
###
GET http://localhost:5000/user/ HTTP/1.1
###
GET http://localhost:5000/user/FedeSca001 HTTP/1.1
###
GET http://localhost:5000/user/FedeSca001/lcdtm1234 HTTP/1.1